#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs npm run format --

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
