name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run test:coverage
      - run: npm run test:mutation
